### ISSUE TITLE
Apache error `client denied by server configuration`

### ISSUE THREAD

**Issue by vboctor** [mantisbt-plugins/Snippets#40] opened 2018-05-01 01:52 UTC
This following error shows up in `/var/log/apache/errors.log` when there are no defined Snippets for user or globally.  In such case, the error is generated and the Snippets dropdown is visible with one entry `--`.  The expected behavior should be to not show the Snippets dropdown and not generate an error.

```
[Tue  May 01 00:54:21.066773 2018] [authz_core:error] [pid 20615] [client  172.31.34.65:45273] AH01630: client denied by server configuration:  /.../www/plugins/Snippets/data,  referer: https://mantisbt/view.php?id=761
```

**Comment by dregad** [comment] 2018-05-01 07:33
I am not able to reproduce this, despite having deleted all snippets from the system. 


It is unlikely that the AH01630 error would be caused by the lack of defined snippets for the current user, as this is usually triggered by Apache / .htaccess configuration.

**Comment by dregad** [comment] 2018-05-01 07:49
>  The expected behavior should be to not show the Snippets dropdown and not generate an error.

This was supposed to have been fixed in #24, but it would appear that it has not. I have opened #41 to track that.

**Comment by dregad** [comment] 2018-05-23 07:00
As mentioned before, the Apache error is not triggered by the plugin AFAICT. The other issue has been fixed in v2.2.5, so I don't see any reason not to close this. Feel free to reopen with additional info if the problem persists.

**Closed by dregad** 2018-05-23 07:00 UTC
Labels: no change required

**Comment by TomR** [comment] 2020-03-19 21:38
From logging:

[Thu Mar 19 22:30:13.212322 2020] [authz_core:error] [pid 62105:tid 140042374379264] [client xx.xxx.xx.xx:61721] AH01630: client denied by server configuration: /home/customer/domains/domain.com/private_html/plugins/Snippets/data, referer: https://domain.com/view.php?id=7549

It seems there is referred to a subdirectory data.
When i create a empty folder data the error in apache logging dissapear

**Comment by dregad** [comment] 2020-03-21 17:21
> It seems there is referred to a subdirectory data

@TomR It's not an actual subdirectory, it's a REST API endpoint as [defined in the plugin's routes method](https://github.com/mantisbt-plugins/Snippets/blob/v2.2.5/Snippets.php#L111). The client-side path should be http://path.to/mantis/api/rest/index.php/plugins/Snippets/data.

I still don't have steps to reproduce...

**Comment by TomR** [comment] 2023-02-11 20:10
I guess it is due to .htaccess in plugings directory.
After commenting #Require all denied the error dissapear.
