### ISSUE TITLE
Snippets Plugin - update error

### ISSUE THREAD

**Issue by jmascheri** [mantisbt-plugins/snippets#15] opened 2017-02-07 20:21 UTC
The snippets plugin is recognized by mantis but shows as being out of date. When clicking the update button the following error is shown on the page:

"APPLICATION ERROR #2503
Upgrading the plugin schema failed in block #0.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section."

When clicking the plugin name to try to configure it, the following error is shown:

"APPLICATION ERROR #2505
The "Snippets" plugin needs to be upgraded before you can access this page.
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section."

![snippets_error](https://cloud.githubusercontent.com/assets/7049122/22709785/e4a2ec0e-ed2f-11e6-84d3-208f10a53a92.png)

**Comment by jmascheri** [comment] 2017-02-07 20:22
NOTE:  This issue is for Mantisbt Version 2.1.0

**Comment by dregad** [comment] 2017-02-08 09:24
1. Is this a new install of Mantis 2.1, or an upgrade from an earlier version ?
2. Are you using the plugin code from the _modern-ui_ branch ?

**Comment by jmascheri** [comment] 2017-02-08 15:43
1. This was an upgrade from Mantis 2.0.
2. Yes, I grabbed the modern-ui branch version.

Please let me know if there is anything else I can do to help. :)

**Comment by dregad** [comment] 2017-07-31 16:00
I am not able to reproduce this, plugin installs just fine for me. 

Since it's been 6 months, I'm going to close this issue. Feel free to reopen if the problem persists, providing steps to reproduce the error.

**Closed by dregad** 2017-07-31 16:00 UTC
